version: "3.3"

services:

  ckb-node:
    image: nervos/ckb:v0.121.0
    ports: 
      - "8114:8114" # RPC
      - "8115:8115" # Blockchain
    networks:
      - default
    environment:
      CKB_CHAIN: "mainnet"
    volumes:
      - "./ckb-node/mainnet:/var/lib/ckb"
    command: ["run"]
    restart: always
    

  influxdb2:
    image: influxdb:2.7.11
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: fi5
      DOCKER_INFLUXDB_INIT_BUCKET: init-bucket
    volumes:
      - "./influxdb2/data:/var/lib/influxdb2"
      - "./influxdb2/config:/etc/influxdb2"
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    user: "1000:1000"
    networks:
      - default
    restart: always
      
  fi5pool:
    image: registry.devops.rivtower.com/fi5pool/fi5pool:v0.3.7
    ports:
      - "4610:4610"
      - "8888:8888"
    working_dir: /opt
    volumes:
      - "./fi5pool/config:/opt"
      - "./fi5pool/logs:/tmp/logs"
    networks:
      - default
    restart: always

      
secrets:
  influxdb2-admin-username:
    file: ./influxdb2/admin-username
  influxdb2-admin-password:
    file: ./influxdb2/admin-password
  influxdb2-admin-token:
    file: ./influxdb2/admin-token

