# rpc listen port
rpc_listen_port = 34255
# http listen port
http_listen_port = 8888
# rpc url of the ckb node
ckb_rpc_url = "http://127.0.0.1:8114"
# difficulty of the pool
difficulty = 800_000
# interval of pulling block template
pull_block_template_interval = 5000
# interval of save log
log_interval = 120
# rpc timeout
rpc_timeout = 2000
# rpc retry times
rpc_retry_times = 5
# alert url, if set, will send alert message to this url
alert_url = ""

# block assembler configuration
[block_assembler]
code_hash = "0x"
args = "0x"
hash_type = "type"
message = "0x"

# influxdb configuration, if set, will write share and block to influxdb
[influx]
url = "http://127.0.0.1:4620"
org = ""
token = ""
share_bucket = "share-bucket"
block_bucket = "block-bucket"
log_bucket = "log-bucket"

# log configuration
[log_config]
# log filter
filter = "info"
# rolling file configuration, index 0 is for log file directory, index 1 is for log file name prefix
rolling_file = ["./logs", "fi5pool"]

# mailer configuration, if set, will send alert message to this mailer
[mailer]
username = ""
password = ""
relay = ""
